name: HTTP-SERVER CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  

jobs:
  image_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag capriciousduck/http-server:latest
    - name: Docker Login
      env:
            DOCKER_USER: ${{secrets.DOCKER_USER}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
            
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker image push
      run: docker push capriciousduck/http-server:latest
